### ISSUE TITLE
Faraday Constant in Currents

### ISSUE THREAD

**Issue by smaasz** [j-fu/LiquidElectrolytes.jl#26]
In the computation of the currents from an `IVSweepResult` the `Unitful.jl` physics constant `F` is used:
https://github.com/j-fu/LiquidElectrolytes.jl/blob/c772d3ecd1dd846451a3d52c4db3ca7f46051549/src/cells.jl#L252

From the source code in `Unitful.jl` it is clear that the value is that of one Farad in SI units:
https://github.com/PainterQubits/Unitful.jl/blob/a09bdaac255d456e6315b77979a48956aca1d3a3/src/pkgdefaults.jl#L174

A quick test yields
```julia
julia> using LessUnitful.jl; ph"F"
1.0
```

**Comment by j-fu** [comment]
Thank you, fixed in https://github.com/j-fu/LiquidElectrolytes.jl/commit/04e02175b9248e6bea24f0dc93585f197975a16c
